import { Toaster } from 'sonner';

import '../globals.css';
import AuthProvider from '@/components/ui/provider/ProviderLayout';

export const metadata = {
  title: 'Toss',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="grid min-h-[100dvh] grid-rows-[auto_1fr] bg-light-500">
          <Toaster richColors closeButton position="top-center" />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
