import { Toaster } from "sonner";

import "../globals.css";
import MuiProvider from "@/components/provider/MuiProvider";

export const metadata = {
  title: "Toss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#fff] min-h-screen">
        <MuiProvider>
          <Toaster richColors closeButton position="top-center" />
          {children}
        </MuiProvider>
      </body>
    </html>
  );
}
