import { Toaster } from 'sonner';
import Navbar from '@/components/Navbar';

import '../globals.css';
import CategoryLinks from '@/components/CategoryLinks';
import CategoryList from '@/components/CategoryList';

export const metadata = {
  title: 'Toss',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid min-h-[100dvh] grid-rows-[auto_1fr] bg-light-500">
        <Toaster richColors closeButton position="top-center" />
        <Navbar/>
        <CategoryLinks/>
        <CategoryList/>
        {children}
      </body>
    </html>
  );
}
